language: Java
# script:
#   - mvn install

env:
  global:
    secure: dwTMWYLM46JKVh+vYkX++umkVaXTlOELou6UB63ORBIcl4pgCI3M/JSwfuLk9GyGciE6hp8Y2uTv55k8slGvW6TPSk5ieD5y1/rWikk3W+E4tlJzes1IgGQcmBi98QMbRWQ+eSm+YSymBFkx2JeqPY8tZImKED5uzTPaxH29Iit3gHOrh2Tc9gDFruSx3LuVmXd9LEkp6/Wc9GzE9JQTfbUvvbfj53BIWLCB5RADIi4NvetNeeArC084OJPgOCQS9bd98bBzbsQdW1oD0dEAdLZt2QJb2pjPNXmMM1FRG15E6ZNOfbl61V1k8ZwsBE7WnYT0U9EQpdbP/jIP/XraXTa1M3N1E9draI+2CFq/YxzvlmUY5pklvDp3euJjXrLjp7L81UQk1ZVxUk8zlUo1kgFDPTwwnr5C/WHV6hK/YRiEiMjYuKVKB7vCckhya4DuGsrD1RmcrhL6SmxrDwfb+jdYtDUT9ZhdBSHB/5G0cHdoewtv9LKkXe9oxp3QPQb1AyFUsb+fo4ny1QQlf10Xc5IMrpHPYrsJrUdlNR6JSI7MEuW7Al6NQt3yEquUdK/t7YYxt/EB+NBfTMVIorfNsqI4nq91wtj1SxuPQ8N9qD7mcLPdouSEkbRk1c0ihSb5e091bpQn4z2K1oVv049iNrVKg9R1vb40cZ+AUucY/Xw=

after_success: - .utils/publish-docs.sh